# Generated by Django 5.1.2 on 2024-10-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AModle',
            new_name='Restaurant',
        ),
    ]
